// File generated by FlutterFire CLI with placeholder values for local development.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'mock-api-key-for-local-dev-only-value',
    appId: '1:123456789000:web:abcdef123456',
    messagingSenderId: '123456789000',
    projectId: 'splitico',
    authDomain: 'splitico.firebaseapp.com',
    storageBucket: 'splitico.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'mock-api-key-for-local-dev-only-value',
    appId: '1:123456789000:android:abcdef123456',
    messagingSenderId: '123456789000',
    projectId: 'splitico',
    storageBucket: 'splitico.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'mock-api-key-for-local-dev-only-value',
    appId: '1:123456789000:ios:abcdef123456',
    messagingSenderId: '123456789000',
    projectId: 'splitico',
    storageBucket: 'splitico.appspot.com',
    iosBundleId: 'com.example.splitico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'mock-api-key-for-local-dev-only-value',
    appId: '1:123456789000:ios:abcdef123456',
    messagingSenderId: '123456789000',
    projectId: 'splitico',
    storageBucket: 'splitico.appspot.com',
    iosBundleId: 'com.example.splitico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'mock-api-key-for-local-dev-only-value',
    appId: '1:123456789000:windows:abcdef123456',
    messagingSenderId: '123456789000',
    projectId: 'splitico',
    storageBucket: 'splitico.appspot.com',
  );
}
