// File generated by FlutterFire CLI with placeholder values for local development.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVlcvg6SyYZkRYFPxL4BQiLRs4nS58A-c',
    appId: '1:794278224451:web:9fc26a15b7379155f1eaf6',
    messagingSenderId: '794278224451',
    projectId: 'splitico-5d46f',
    authDomain: 'splitico-5d46f.firebaseapp.com',
    storageBucket: 'splitico-5d46f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjL1sQNc1ChR1R4-b8dwI0ftEMTlfjT_4',
    appId: '1:794278224451:android:b45d6fea9550d2e4f1eaf6',
    messagingSenderId: '794278224451',
    projectId: 'splitico-5d46f',
    storageBucket: 'splitico-5d46f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF3A01pSNA-fwRrdDKIO3jjxNwvoPC5rA',
    appId: '1:794278224451:ios:8d2a30636368e280f1eaf6',
    messagingSenderId: '794278224451',
    projectId: 'splitico-5d46f',
    storageBucket: 'splitico-5d46f.firebasestorage.app',
    iosBundleId: 'com.example.splitico',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF3A01pSNA-fwRrdDKIO3jjxNwvoPC5rA',
    appId: '1:794278224451:ios:8d2a30636368e280f1eaf6',
    messagingSenderId: '794278224451',
    projectId: 'splitico-5d46f',
    storageBucket: 'splitico-5d46f.firebasestorage.app',
    iosBundleId: 'com.example.splitico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVlcvg6SyYZkRYFPxL4BQiLRs4nS58A-c',
    appId: '1:794278224451:web:0e47e595e53bb485f1eaf6',
    messagingSenderId: '794278224451',
    projectId: 'splitico-5d46f',
    authDomain: 'splitico-5d46f.firebaseapp.com',
    storageBucket: 'splitico-5d46f.firebasestorage.app',
  );
}
